
import { GoogleGenAI } from "@google/genai";
import { AspectRatio } from "../types";

export const generateIcon = async (
  text: string, 
  stylePrompt: string, 
  aspectRatio: AspectRatio = '16:9'
): Promise<string> => {
  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY || '' });
  
  // Construct the prompt for high-quality horizontal icons
  const prompt = `A professional horizontal icon logo. The central element is the text "${text}". ${stylePrompt}. Ensure the text is perfectly spelled and legible. High resolution, crisp edges, cinematic lighting.`;

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          { text: prompt }
        ],
      },
      config: {
        imageConfig: {
          aspectRatio: aspectRatio,
        }
      },
    });

    let imageUrl = '';
    
    // Iterate through parts to find the image
    const candidates = response.candidates;
    if (candidates && candidates.length > 0) {
      const parts = candidates[0].content.parts;
      for (const part of parts) {
        if (part.inlineData) {
          imageUrl = `data:image/png;base64,${part.inlineData.data}`;
          break;
        }
      }
    }

    if (!imageUrl) {
      throw new Error("No image was generated by the model.");
    }

    return imageUrl;
  } catch (error) {
    console.error("Gemini API Error:", error);
    throw error;
  }
};
